<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Target Name="ILRepacker" AfterTargets="Build">
		<PropertyGroup>
			<ILRepackLibPath>$(OutputPath);$(USERPROFILE)\.nuget\packages\jotunnlib\2.26.1\lib\net462;$(BEPINEX_PATH)\core;$(BEPINEX_PATH)\plugins;$(VALHEIM_MANAGED)</ILRepackLibPath>
		</PropertyGroup>
		<ItemGroup>
			<InputAssemblies Include="$(TargetPath)" />
			<InputAssemblies Include="$(OutputPath)\ServerSync.dll" />
		</ItemGroup>
		<ILRepack
  Parallel="true"
    DebugInfo="true"
   Internalize="true"
      InputAssemblies="@(InputAssemblies)"
       OutputFile="$(TargetPath)"
            TargetKind="SameAsPrimaryAssembly"
          LibraryPath="$(ILRepackLibPath)" />
	</Target>
</Project>